version: '3.8'
services:
  myapp:
    image:  my-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-app-example
    ports:
      - "8081:8080"
    volumes:
      - ./app.war:/usr/local/tomcat/myapps/app.war 
