FROM tomcat:9.0.8-jre8-alpine
LABEL maintainer="blogruben"

ADD app.war /usr/local/tomcat/webapps/
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

EXPOSE 8080
CMD ["catalina.sh", "run"]
