version: '3.8'
services:
  myapp:
    image:  my-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-app-example
    ports:
      - "8443:8443"
    volumes:
      - ./docker/app.war:/usr/local/tomcat/webapps/app.war 
