version: '3.8'
services:
  myapp:
    image:  my-app
    build:
      context: ./docker
      dockerfile: Dockerfile.server
    container_name: tomcat-app-example
    ports:
      - "8081:8080"
    volumes:
      - ./docker/app.war:/usr/local/tomcat/webapps/app.war 
      - ./docker/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml