version: '3'
services:
  dev:
    image: tomcat:8.0-alpine
    ports:
      - "8081:8080"
    volumes:
      - ./docker/server.xml:/usr/local/tomcat/conf/server.xml
      - ./docker/sample.war:/usr/local/tomcat/webapps/sample.war